library(xlsx)
data <- read.xlsx("data.xlsx", 1)
datareopen <- data[c(116:281), ]
png(file = "bxretailvscasesreopen.png")
plot(x = datareopen$bronx_retail_and_recreation_percent_change_from_baseline, y = datareopen$BX_CASE_COUNT, col = "blue", main = "Bronx Retail and Recreation Change vs COVID19 Cases")
abline(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_retail_and_recreation_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_retail_and_recreation_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bxgroceryvscasesreopen.png")
plot(x = datareopen$bronx_grocery_and_pharmacy_percent_change_from_baseline, y = datareopen$BX_CASE_COUNT, col = "blue", main = "Bronx Grocery and Pharmacy Change vs COVID19 Cases")
abline(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_grocery_and_pharmacy_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_grocery_and_pharmacy_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bxparksvscasesreopen.png")
plot(x = datareopen$bronx_parks_percent_change_from_baseline, y = datareopen$BX_CASE_COUNT, col = "blue", main = "Bronx Parks Change vs COVID19 Cases")
abline(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_parks_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_parks_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bxtransitvscasesreopen.png")
plot(x = datareopen$bronx_transit_stations_percent_change_from_baseline, y = datareopen$BX_CASE_COUNT, col = "blue", main = "Bronx Transit Stations Change vs COVID19 Cases")
abline(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_transit_stations_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_transit_stations_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bxworkplacesvscasesreopen.png")
plot(x = datareopen$bronx_workplaces_percent_change_from_baseline, y = datareopen$BX_CASE_COUNT, col = "blue", main = "Bronx Workplaces Change vs COVID19 Cases")
abline(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_workplaces_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_workplaces_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bxresidentialvscasesreopen.png")
plot(x = datareopen$bronx_residential_percent_change_from_baseline, y = datareopen$BX_CASE_COUNT, col = "blue", main = "Bronx Residential Change vs COVID19 Cases")
abline(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_residential_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BX_CASE_COUNT~datareopen$bronx_residential_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bkretailvscasesreopen.png")
plot(x = datareopen$brooklyn_retail_and_recreation_percent_change_from_baseline, y = datareopen$BK_CASE_COUNT, col = "blue", main = "Brooklyn Retail and Recreation Change vs COVID19 Cases")
abline(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_retail_and_recreation_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_retail_and_recreation_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bkgroceryvscasesreopen.png")
plot(x = datareopen$brooklyn_grocery_and_pharmacy_percent_change_from_baseline, y = datareopen$BK_CASE_COUNT, col = "blue", main = "Brooklyn Grocery and Pharmacy Change vs COVID19 Cases")
abline(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_grocery_and_pharmacy_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_grocery_and_pharmacy_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bkparksvscasesreopen.png")
plot(x = datareopen$brooklyn_parks_percent_change_from_baseline, y = datareopen$BK_CASE_COUNT, col = "blue", main = "Brooklyn Parks Change vs COVID19 Cases")
abline(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_parks_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_parks_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bktransitvscasesreopen.png")
plot(x = datareopen$brooklyn_transit_stations_percent_change_from_baseline, y = datareopen$BK_CASE_COUNT, col = "blue", main = "Brooklyn Transit Stations Change vs COVID19 Cases")
abline(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_transit_stations_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_transit_stations_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bkworkplacesvscasesreopen.png")
plot(x = datareopen$brooklyn_workplaces_percent_change_from_baseline, y = datareopen$BK_CASE_COUNT, col = "blue", main = "Brooklyn Workplaces Change vs COVID19 Cases")
abline(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_workplaces_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_workplaces_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "bkresidentialvscasesreopen.png")
plot(x = datareopen$brooklyn_residential_percent_change_from_baseline, y = datareopen$BK_CASE_COUNT, col = "blue", main = "Brooklyn Residential Change vs COVID19 Cases")
abline(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_residential_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$BK_CASE_COUNT~datareopen$brooklyn_residential_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "mnretailvscasesreopen.png")
plot(x = datareopen$manhattan_retail_and_recreation_percent_change_from_baseline, y = datareopen$MN_CASE_COUNT, col = "blue", main = "Manhattan Retail and Recreation Change vs COVID19 Cases")
abline(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_retail_and_recreation_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_retail_and_recreation_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "mngroceryvscasesreopen.png")
plot(x = datareopen$manhattan_grocery_and_pharmacy_percent_change_from_baseline, y = datareopen$MN_CASE_COUNT, col = "blue", main = "Manhattan Grocery and Pharmacy Change vs COVID19 Cases")
abline(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_grocery_and_pharmacy_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_grocery_and_pharmacy_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "mnparksvscasesreopen.png")
plot(x = datareopen$manhattan_parks_percent_change_from_baseline, y = datareopen$MN_CASE_COUNT, col = "blue", main = "Manhattan Parks Change vs COVID19 Cases")
abline(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_parks_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_parks_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "mntransitvscasesreopen.png")
plot(x = datareopen$manhattan_transit_stations_percent_change_from_baseline, y = datareopen$MN_CASE_COUNT, col = "blue", main = "Manhattan Transit Stations Change vs COVID19 Cases")
abline(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_transit_stations_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_transit_stations_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "mnworkplacesvscasesreopen.png")
plot(x = datareopen$manhattan_workplaces_percent_change_from_baseline, y = datareopen$MN_CASE_COUNT, col = "blue", main = "Manhattan Workplaces Change vs COVID19 Cases")
abline(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_workplaces_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_workplaces_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "mnresidentialvscasesreopen.png")
plot(x = datareopen$manhattan_residential_percent_change_from_baseline, y = datareopen$MN_CASE_COUNT, col = "blue", main = "Manhattan Residential Change vs COVID19 Cases")
abline(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_residential_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$MN_CASE_COUNT~datareopen$manhattan_residential_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "qnretailvscasesreopen.png")
plot(x = datareopen$queens_retail_and_recreation_percent_change_from_baseline, y = datareopen$QN_CASE_COUNT, col = "blue", main = "Queens Retail and Recreation Change vs COVID19 Cases")
abline(lm(datareopen$QN_CASE_COUNT~datareopen$queens_retail_and_recreation_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$QN_CASE_COUNT~datareopen$queens_retail_and_recreation_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "qngroceryvscasesreopen.png")
plot(x = datareopen$queens_grocery_and_pharmacy_percent_change_from_baseline, y = datareopen$QN_CASE_COUNT, col = "blue", main = "Queens Grocery and Pharmacy Change vs COVID19 Cases")
abline(lm(datareopen$QN_CASE_COUNT~datareopen$queens_grocery_and_pharmacy_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$QN_CASE_COUNT~datareopen$queens_grocery_and_pharmacy_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "qnparksvscasesreopen.png")
plot(x = datareopen$queens_parks_percent_change_from_baseline, y = datareopen$QN_CASE_COUNT, col = "blue", main = "Queens Parks Change vs COVID19 Cases")
abline(lm(datareopen$QN_CASE_COUNT~datareopen$queens_parks_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$QN_CASE_COUNT~datareopen$queens_parks_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "qntransitvscasesreopen.png")
plot(x = datareopen$queens_transit_stations_percent_change_from_baseline, y = datareopen$QN_CASE_COUNT, col = "blue", main = "Queens Transit Stations Change vs COVID19 Cases")
abline(lm(datareopen$QN_CASE_COUNT~datareopen$queens_transit_stations_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$QN_CASE_COUNT~datareopen$queens_transit_stations_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "qnworkplacesvscasesreopen.png")
plot(x = datareopen$queens_workplaces_percent_change_from_baseline, y = datareopen$QN_CASE_COUNT, col = "blue", main = "Queens Workplaces Change vs COVID19 Cases")
abline(lm(datareopen$QN_CASE_COUNT~datareopen$queens_workplaces_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$QN_CASE_COUNT~datareopen$queens_workplaces_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "qnresidentialvscasesreopen.png")
plot(x = datareopen$queens_residential_percent_change_from_baseline, y = datareopen$QN_CASE_COUNT, col = "blue", main = "Queens Residential Change vs COVID19 Cases")
abline(lm(datareopen$QN_CASE_COUNT~datareopen$queens_residential_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$QN_CASE_COUNT~datareopen$queens_residential_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "siretailvscasesreopen.png")
plot(x = datareopen$staten_island_retail_and_recreation_percent_change_from_baseline, y = datareopen$SI_CASE_COUNT, col = "blue", main = "Staten Island Retail and Recreation Change vs COVID19 Cases")
abline(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_retail_and_recreation_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_retail_and_recreation_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "sigroceryvscasesreopen.png")
plot(x = datareopen$staten_island_grocery_and_pharmacy_percent_change_from_baseline, y = datareopen$SI_CASE_COUNT, col = "blue", main = "Staten Island Grocery and Pharmacy Change vs COVID19 Cases")
abline(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_grocery_and_pharmacy_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_grocery_and_pharmacy_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "siparksvscasesreopen.png")
plot(x = datareopen$staten_island_parks_percent_change_from_baseline, y = datareopen$SI_CASE_COUNT, col = "blue", main = "Staten Island Parks Change vs COVID19 Cases")
abline(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_parks_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_parks_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "sitransitvscasesreopen.png")
plot(x = datareopen$staten_island_transit_stations_percent_change_from_baseline, y = datareopen$SI_CASE_COUNT, col = "blue", main = "Staten Island Transit Stations Change vs COVID19 Cases")
abline(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_transit_stations_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_transit_stations_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "siworkplacesvscasesreopen.png")
plot(x = datareopen$staten_island_workplaces_percent_change_from_baseline, y = datareopen$SI_CASE_COUNT, col = "blue", main = "Staten Island Workplaces Change vs COVID19 Cases")
abline(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_workplaces_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_workplaces_percent_change_from_baseline))$adj.r.squared))
dev.off()
png(file = "siresidentialvscasesreopen.png")
plot(x = datareopen$staten_island_residential_percent_change_from_baseline, y = datareopen$SI_CASE_COUNT, col = "blue", main = "Staten Island Residential Change vs COVID19 Cases")
abline(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_residential_percent_change_from_baseline), col="blue")
legend("topright", legend = paste("R²=", summary(lm(datareopen$SI_CASE_COUNT~datareopen$staten_island_residential_percent_change_from_baseline))$adj.r.squared))
dev.off()