library(xlsx)
data <- read.xlsx("data.xlsx", 1)

# Retail/Recreation Cases
png(file = "bxretailvscaseslog.png")
plot(x = log(data$bronx_retail_and_recreation_percent_change_from_baseline + 80), y = log(data$BX_CASE_COUNT + 1), col = "blue", main = "Bronx Retail and Recreation Change vs COVID19 Cases")
abline(lm(log(data$BX_CASE_COUNT + 1)~log(data$bronx_retail_and_recreation_percent_change_from_baseline + 80)), col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$BX_CASE_COUNT + 1)~log(data$bronx_retail_and_recreation_percent_change_from_baseline + 80)))$adj.r.squared))
dev.off()
png(file = "bkretailvscaseslog.png")
plot(x = log(data$brooklyn_retail_and_recreation_percent_change_from_baseline + 80), y = log(data$BK_CASE_COUNT + 1), col = "blue", main = "Brooklyn Retail and Recreation Change vs COVID19 Cases")
abline(lm(log(data$BK_CASE_COUNT + 1)~log(data$brooklyn_retail_and_recreation_percent_change_from_baseline + 80)), col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$BK_CASE_COUNT + 1)~log(data$brooklyn_retail_and_recreation_percent_change_from_baseline + 80)))$adj.r.squared))
dev.off()
png(file = "mnretailvscaseslog.png")
plot(x = log(data$manhattan_retail_and_recreation_percent_change_from_baseline + 100), y = log(data$MN_CASE_COUNT + 1), col = "blue", main = "Manhattan Retail and Recreation Change vs COVID19 Cases")
abline(lm(log(data$MN_CASE_COUNT + 1)~log(data$manhattan_retail_and_recreation_percent_change_from_baseline + 100)), col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$MN_CASE_COUNT + 1)~log(data$manhattan_retail_and_recreation_percent_change_from_baseline + 100)))$adj.r.squared))
dev.off()
png(file = "qnretailvscaseslog.png")
plot(x = log(data$queens_retail_and_recreation_percent_change_from_baseline + 80), y = log(data$QN_CASE_COUNT + 1), col = "blue", main = "Queens Retail and Recreation Change vs COVID19 Cases")
abline(lm(log(data$QN_CASE_COUNT + 1)~log(data$queens_retail_and_recreation_percent_change_from_baseline + 80)), col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$QN_CASE_COUNT + 1)~log(data$queens_retail_and_recreation_percent_change_from_baseline + 80)))$adj.r.squared))
dev.off()
png(file = "siretailvscaseslog.png")
plot(x = log(data$staten_island_retail_and_recreation_percent_change_from_baseline + 80), y = log(data$SI_CASE_COUNT + 1), col = "blue", main = "Staten Island Retail and Recreation Change vs COVID19 Cases")
abline(lm(log(data$SI_CASE_COUNT + 1)~log(data$staten_island_retail_and_recreation_percent_change_from_baseline + 80)), col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$SI_CASE_COUNT + 1)~log(data$staten_island_retail_and_recreation_percent_change_from_baseline + 80)))$adj.r.squared))
dev.off()


# Residential Cases
png(file = "bxresidentialvscaseslog.png")
plot(x = log(data$bronx_residential_percent_change_from_baseline + 2), y = log(data$BX_CASE_COUNT + 1), col = "blue", main = "Bronx Residential Change vs COVID19 Cases")
abline(lm(log(data$BX_CASE_COUNT + 1)~log(data$bronx_residential_percent_change_from_baseline + 2)), untf=F, col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$BX_CASE_COUNT + 1)~log(data$bronx_residential_percent_change_from_baseline + 2)))$adj.r.squared))
dev.off()
png(file = "bkresidentialvscaseslog.png")
plot(x = log(data$brooklyn_residential_percent_change_from_baseline + 2), y = log(data$BK_CASE_COUNT + 1), col = "blue", main = "Brooklyn Residential Change vs COVID19 Cases")
abline(lm(log(data$BK_CASE_COUNT + 1)~log(data$brooklyn_residential_percent_change_from_baseline + 2)), untf=F, col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$BK_CASE_COUNT + 1)~log(data$brooklyn_residential_percent_change_from_baseline + 2)))$adj.r.squared))
dev.off()
png(file = "mnresidentialvscaseslog.png")
plot(x = log(data$manhattan_residential_percent_change_from_baseline + 1), y = log(data$MN_CASE_COUNT + 1), col = "blue", main = "Manhattan Residential Change vs COVID19 Cases")
abline(lm(log(data$MN_CASE_COUNT + 1)~log(data$manhattan_residential_percent_change_from_baseline + 1)), untf=F, col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$MN_CASE_COUNT + 1)~log(data$manhattan_residential_percent_change_from_baseline + 1)))$adj.r.squared))
dev.off()
png(file = "qnresidentialvscaseslog.png")
plot(x = log(data$queens_residential_percent_change_from_baseline + 1), y = log(data$QN_CASE_COUNT + 1), col = "blue", main = "Queens Residential Change vs COVID19 Cases")
abline(lm(log(data$QN_CASE_COUNT + 1)~log(data$queens_residential_percent_change_from_baseline + 1)), untf=F, col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$QN_CASE_COUNT + 1)~log(data$queens_residential_percent_change_from_baseline + 1)))$adj.r.squared))
dev.off()
png(file = "siresidentialvscaseslog.png")
plot(x = log(data$staten_island_residential_percent_change_from_baseline + 2), y = log(data$SI_CASE_COUNT + 1), col = "blue", main = "Staten Island Residential Change vs COVID19 Cases")
abline(lm(log(data$SI_CASE_COUNT + 1)~log(data$staten_island_residential_percent_change_from_baseline + 2)), untf=F, col="blue")
legend("topright", legend = paste("R²=", summary(lm(log(data$SI_CASE_COUNT + 1)~log(data$staten_island_residential_percent_change_from_baseline + 2)))$adj.r.squared))
dev.off()